/**
 * Skills — grouped for the grid, five sections.
 *
 * Rules:
 *  - Only skills carrying IDEA.md evidence appear.
 *  - `icon` maps to TechIconKey (generated by scripts/generate-tech-icons.mjs).
 *  - `image` is for marks that are not in simple-icons: a raster file in public/.
 *  - No proficiency labels: the grid shows mark + name only.
 *  - Never claim full-stack ownership: in both Laravel projects the backend was
 *    built by a teammate.
 *
 * Notable mapping decisions:
 *  - Blade uses the Laravel mark. Blade ships with Laravel; its own "logo" is
 *    just the Laravel mark, so using Laravel's is accurate, not a shortcut.
 *  - AI Agent uses the Hermes Agent logo (public/logos/hermes.png) — the agent
 *    framework used for the work on this site.
 *  - ESP32 shares the Arduino mark. In this project the board is programmed
 *    through the Arduino IDE, so the mark is accurate rather than a shortcut.
 *  - C, MySQL, VS Code, Excel and Hermes use raster marks in public/logos/,
 *    because those marks are not in simple-icons. Sources and licences are
 *    recorded in public/logos/README.md.
 */

import type { TechIconKey } from "@/components/ui/TechIcon";

export interface Skill {
  name: string;
  /** simple-icons mark, by key. Omit when the skill has none. */
  icon?: TechIconKey;
  /** Raster mark in public/ for anything not covered by simple-icons. */
  image?: string;
}

export interface SkillGroup {
  group: string;
  items: Skill[];
}

export const skillGroups: SkillGroup[] = [
  {
    group: "Languages",
    items: [
      { name: "JavaScript", icon: "javascript" },
      { name: "TypeScript", icon: "typescript" },
      { name: "PHP", icon: "php" },
      { name: "Python", icon: "python" },
      { name: "C", image: "/logos/c.png" },
      { name: "SQL & Relational DB", icon: "postgresql" },
    ],
  },
  {
    group: "Frameworks & Runtimes",
    items: [
      { name: "Laravel", icon: "laravel" },
      { name: "Next.js", icon: "nextjs" },
      { name: "React", icon: "react" },
      { name: "Node.js", icon: "nodejs" },
    ],
  },
  {
    group: "Markup & Styling",
    items: [
      { name: "HTML5", icon: "html5" },
      { name: "CSS3", icon: "css" },
      { name: "Tailwind CSS", icon: "tailwindcss" },
      { name: "Blade", icon: "laravel" },
    ],
  },
  {
    group: "Tools",
    items: [
      { name: "Git & Version Control", icon: "git" },
      { name: "GitHub", icon: "github" },
      { name: "Postman", icon: "postman" },
      { name: "Figma", icon: "figma" },
      { name: "Vercel Deployment", icon: "vercel" },
      { name: "VS Code", image: "/logos/vscode.png" },
      { name: "Arduino IDE", icon: "arduino" },
      { name: "ESP32", icon: "arduino" },
    ],
  },
  {
    group: "AI / LLM",
    items: [
      { name: "PyTorch", icon: "pytorch" },
      { name: "Hugging Face Transformers", icon: "huggingface" },
      { name: "PEFT", icon: "huggingface" },
      { name: "TRL", icon: "huggingface" },
      { name: "Unsloth", icon: "huggingface" },
      { name: "AI Agent", image: "/logos/hermes.png" },
      { name: "Data Preprocessing", image: "/logos/excel.png" },
    ],
  },
];
